Repository Qytera-Gmbh/QTAF, pull requests merged in 2023-08, with the labels that each got.

#150 Check secrets availability before running tests
  .github/workflows/Test.yml
Labels: enhancement

#137 Support dynamic injection of page objects
  pom.xml
  qtaf-allure-plugin/pom.xml
  qtaf-aws-devicefarm/pom.xml
  qtaf-core/pom.xml
  qtaf-core/src/main/java/de/qytera/qtaf/testng/context/QtafTestNGContext.java
  qtaf-core/src/test/java/de/qytera/qtaf/testng/context/QtafTestNGContextTest.java
  qtaf-data/pom.xml
  qtaf-html-report-plugin/pom.xml
  qtaf-http/pom.xml
  qtaf-io/pom.xml
  qtaf-security/pom.xml
  qtaf-testrail-plugin/pom.xml
  qtaf-xray-plugin/pom.xml
Labels: enhancement, 🛠 core

#154 Bump QTAF from 0.1.1 to 0.2.0
  pom.xml
  qtaf-allure-plugin/pom.xml
  qtaf-aws-devicefarm/pom.xml
  qtaf-core/pom.xml
  qtaf-data/pom.xml
  qtaf-html-report-plugin/pom.xml
  qtaf-http/pom.xml
  qtaf-io/pom.xml
  qtaf-security/pom.xml
  qtaf-testrail-plugin/pom.xml
  qtaf-xray-plugin/pom.xml
Labels: version
