Repository Qytera-Gmbh/QTAF, pull requests merged in 2023-09, with the labels that each got.

#106 Add option to automatically assign test execution issues to preconfigured users
  qtaf-core/src/main/resources/qtaf.json
  qtaf-xray-plugin/pom.xml
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/RequestBodyBuilder.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/XrayJsonImportBuilder.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/commands/UploadImportCommand.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/config/XrayConfigHelper.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ApplicationRoleCloudDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ApplicationRoleDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ApplicationRoleServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ComponentCloudDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ComponentDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ComponentServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/GroupCloudDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/GroupDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/GroupServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/IssueTypeCloudDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/IssueTypeDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/IssueTypeServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ProjectCategoryDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ProjectCloudDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ProjectDetailsDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ProjectDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ProjectServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/ScopeDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/SimpleListWrapperDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/UserCloudDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/UserDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/UserServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/VersionCloudDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/VersionDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/VersionServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/request/jira/issues/AdditionalField.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/request/jira/issues/JiraIssueSearchRequestDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/jira/issues/JiraIssueResponseDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/jira/issues/JiraIssueSearchResponseDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/xray/ImportExecutionResultsResponseDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/xray/ImportExecutionResultsResponseServerDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayIterationResultEntityServer.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntity.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntityCloud.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/event_subscriber/AssignTestExecutionIssueSubscriber.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/event_subscriber/UploadResultsSubscriber.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/jira/JiraIssueRepository.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/jira/JiraProjectRepository.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/builder/XrayJsonImportBuilderTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/dto/jira/ProjectDetailsDtoTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/dto/jira/UserCloudDtoTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/event_subscriber/AssignTestExecutionIssueSubscriberTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/event_subscriber/UploadResultSubscriberTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/repository/JiraIssueRepositoryTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/repository/JiraProjectRepositoryTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/util/Mocking.java
Labels: enhancement, 🛠 xray

#92 Add option to configure Jira status for created Xray test execution issues
  qtaf-aws-devicefarm/src/main/java/de/qytera/qtaf/aws_devicefarm/driver/AbstractAWSDeviceFarmDriver.java
  qtaf-aws-devicefarm/src/test/java/de/qytera/qtaf/aws_devicefarm/driver/DriverTest.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/config/helper/QtafTestExecutionConfigHelper.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/collection/TestScenarioLogCollection.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/selenium/AbstractDriver.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/selenium/ChromeDriver.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/context/QtafTestNGContext.java
  qtaf-core/src/main/resources/qtaf.json
  qtaf-core/src/test/java/de/qytera/qtaf/core/selenium/ChromeDriverTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/selenium/DriverTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/selenium/EdgeDriverTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/selenium/FirefoxDriverTest.java
  qtaf-testrail-plugin/src/main/java/de/qytera/qtaf/testrail/event_subscriber/UploadTestsSubscriber.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/config/XrayConfigHelper.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/EntityPropertyDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/FieldMetaDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/HistoryMetadataDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/HistoryMetadataParticipantDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/IssueUpdateDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/JsonTypeDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/StatusCategoryDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/StatusDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/TransitionDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/jira/TransitionsMetaDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/event_subscriber/TransitionImportTestExecutionIssueSubscriber.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/event_subscriber/UploadResultsSubscriber.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/jira/JiraEndpoint.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/jira/JiraIssueRepository.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/event_subscriber/TransitionImportTestExecutionIssueSubscriberTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/event_subscriber/UploadResultSubscriberTest.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/repository/JiraIssueRepositoryTest.java
Labels: enhancement, 🛠 xray

#177 Added default value for headless driver option.
  qtaf-core/src/main/java/de/qytera/qtaf/core/selenium/AbstractDriver.java
Labels: bug

#176 Fixed `getBoolean` in configuration
  qtaf-core/src/main/java/de/qytera/qtaf/core/config/entity/ConfigMap.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/config/ConfigMapTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/config/ConfigurationTest.java
Labels: bug

#178 Removed debugging code
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/StepInformationLogMessage.java
Labels: bug

#179 Bump QTAF from 0.2.3 to 0.2.4
  pom.xml
  qtaf-allure-plugin/pom.xml
  qtaf-aws-devicefarm/pom.xml
  qtaf-core/pom.xml
  qtaf-data/pom.xml
  qtaf-html-report-plugin/pom.xml
  qtaf-http/pom.xml
  qtaf-io/pom.xml
  qtaf-security/pom.xml
  qtaf-testrail-plugin/pom.xml
  qtaf-xray-plugin/pom.xml
Labels: version

#180 Updated gitignore files
  .gitignore
  qtaf-html-report-plugin/.gitignore
Labels: bug

#166 Failed assertions now should make steps fail
  qtaf-core/src/main/java/de/qytera/qtaf/core/guice/method_interceptor/QtafTestNGAnnotatedMethodInterceptor.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/collection/TestScenarioLogCollection.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/AssertionLogMessage.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/StepInformationLogMessage.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/DemoStepClass.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/TestScenarioLogCollectionTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/model/collection/TestScenarioLogCollectionTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/model/message/StepInformationLogMessageTest.java
Labels: bug

#184 Failed Assertions are now recognized by TestNG
  qtaf-core/src/main/java/de/qytera/qtaf/core/event_subscriber/step/StepLoggerSubscriber.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/guice/invokation/StepExecutionInfo.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/guice/method_interceptor/QtafStepMethodInterceptor.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/event_listener/TestNGEventListener.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/events/payload/TestNGTestEventPayload.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/helper/TestResultHelper.java
  qtaf-core/src/test/java/de/qytera/qtaf/testng/TestNGHelperTest.java
Labels: bug

#188 Added null-safety to ThrowableWrapper
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/error/ThrowableWrapper.java
Labels: bug

#187 Bump QTAF from 0.2.4 to 0.2.5
  pom.xml
  qtaf-allure-plugin/pom.xml
  qtaf-aws-devicefarm/pom.xml
  qtaf-core/pom.xml
  qtaf-data/pom.xml
  qtaf-html-report-plugin/pom.xml
  qtaf-http/pom.xml
  qtaf-io/pom.xml
  qtaf-security/pom.xml
  qtaf-testrail-plugin/pom.xml
  qtaf-xray-plugin/pom.xml
Labels: version

#195 Added check if html-Report is enabled in the config file
  qtaf-html-report-plugin/src/main/java/de/qytera/qtaf/htmlreport/event_subscriber/CreateReportSubscriber.java
Labels: bug

#203 Fixed Bugs that prevented results to be uploaded to Xray Cloud
  qtaf-core/src/main/resources/qtaf.json
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/XrayJsonImportBuilder.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/test/MultipleIterationsXrayTestEntityBuilder.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/test/SingleIterationXrayTestEntityBuilder.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/test/XrayTestEntityBuilder.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/config/XrayConfigHelper.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestExecutionInfoEntity.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntity.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntityCloud.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntityServer.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/builder/XrayJsonImportBuilderTest.java
Labels: bug, 🛠 xray

#207 Added colors to log messages
  qtaf-core/src/main/java/de/qytera/qtaf/core/event_subscriber/step/StepLoggerSubscriber.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/event_subscriber/TestNGLoggingSubscriber.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/event_subscriber/UploadResultsSubscriber.java
Labels: 🛠 core

#208 Upgraded version to v0.2.7
  pom.xml
  qtaf-allure-plugin/pom.xml
  qtaf-aws-devicefarm/pom.xml
  qtaf-core/pom.xml
  qtaf-data/pom.xml
  qtaf-html-report-plugin/pom.xml
  qtaf-http/pom.xml
  qtaf-io/pom.xml
  qtaf-security/pom.xml
  qtaf-testrail-plugin/pom.xml
  qtaf-xray-plugin/pom.xml
Labels: version
