Repository Qytera-Gmbh/QTAF, pull requests merged in 2023-06, with the labels that each got.

#119 Run Sonarcloud analysis on `develop`
  .github/workflows/TestJavaVersions.yml
Labels: bug

#118 Fix called workflow definition with `secrets: inherit`
  .github/workflows/Test.yml
Labels: bug

#120 Add JavaDoc verification to build process
  .github/workflows/Publish.yml
  pom.xml
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/test/XrayTestEntityBuilder.java
Labels: enhancement

#109 Add improved HTTP request logging
  qtaf-http/src/main/java/de/qytera/qtaf/http/WebService.java
Labels: enhancement

#110 Prevent Xray plugin from crashing when handling empty scenario logs
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/test/MultipleIterationsXrayTestEntityBuilder.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/builder/XrayJsonImportBuilderTest.java
Labels: bug, 🛠 xray

#124 Update POM structure and dependencies/plugin version
  pom.xml
  qtaf-allure-plugin/pom.xml
  qtaf-core/pom.xml
  qtaf-data/pom.xml
  qtaf-html-report-plugin/pom.xml
  qtaf-http/pom.xml
  qtaf-io/pom.xml
  qtaf-security/pom.xml
  qtaf-xray-plugin/pom.xml
Labels: dependencies
