Repository Qytera-Gmbh/QTAF, pull requests merged in 2023-07, with the labels that each got.

#133 Skip `browser-actions/setup-edge` on ubuntu runners
  .github/workflows/Test.yml
Labels: bug

#88 Qtaf Testrail Plugin
  lombok.config
  pom.xml
  qtaf-allure-plugin/.gitignore
  qtaf-allure-plugin/src/main/java/de/qytera/qtaf/allure/AllureTestResultGenerator.java
  qtaf-core/.gitignore
  qtaf-core/pom.xml
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/StepInformationLogMessage.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/context/QtafTestNGContext.java
  qtaf-core/src/main/resources/qtaf.json
  qtaf-html-report-plugin/.gitignore
  qtaf-http/pom.xml
  qtaf-http/src/main/java/de/qytera/qtaf/http/WebService.java
  qtaf-security/pom.xml
  qtaf-security/src/main/java/de/qytera/qtaf/security/aes/AES.java
  qtaf-testrail-plugin/.gitignore
  qtaf-testrail-plugin/pom.xml
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/annotations/TestRail.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/config/TestRailConfigHelper.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/entity/Attachment.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/entity/Attachments.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/entity/Link.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/event_subscriber/UploadTestsSubscriber.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/utils/APIClient.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/utils/APIException.java
  qtaf-testrail-plugin/src/main/java/de/qytera/testrail/utils/TestRailManager.java
  qtaf-testrail-plugin/src/test/java/de/qytera/testrail/event_subscriber/UploadTestsSubscriberTest.java
  qtaf-testrail-plugin/src/test/java/de/qytera/testrail/util/Mocking.java
  qtaf-testrail-plugin/src/test/java/de/qytera/testrail/utils/ApiClientTest.java
  qtaf-testrail-plugin/src/test/java/de/qytera/testrail/utils/TestRailManagerTest.java
  qtaf-testrail-plugin/src/test/resources/dummyfile.txt
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/request/issues/JiraIssueSearchRequestDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/graphql/GraphQLResponseDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/graphql/GraphQLResponseErrorDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/graphql/GraphQLResponseErrorLocationDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/issues/JiraIssueResponseDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/dto/response/issues/JiraIssueSearchResponseDto.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/jira/JiraIssueRepository.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/xray/XrayCloudAuthenticator.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/xray/XrayTestRepository.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/repository/xray/XrayTestRepositoryCloud.java
Labels: enhancement, 🛠 testrail

#102 Added assertion logging
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/AssertionLogMessage.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/AssertionLogMessageType.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/StepInformationLogMessage.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/context/AssertionContext.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/context/QtafTestNGContext.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/model/message/AssertionLogMessageTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/testng/AssertionContextTest.java
Labels: enhancement

#136 Fix Gson serialization errors introduced in 0.0.10
  qtaf-allure-plugin/src/main/java/de/qytera/qtaf/allure/AllureReportGenerator.java
  qtaf-allure-plugin/src/main/java/de/qytera/qtaf/allure/AllureTestResultGenerator.java
  qtaf-allure-plugin/src/test/java/de/qytera/qtaf/allure/AllureReportGeneratorTest.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/config/entity/ConfigMap.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/GsonFactory.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/IQtafJsonSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/LocalDateSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/StackTraceElementSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/StepAnnotationSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/TestFeatureAnnotationSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/TestScenarioAnnotationSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/ThrowableSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/strategy/QtafGsonExclusionStrategy.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/guice/QtafModule.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/collection/TestSuiteLogCollection.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/reflection/ClassLoader.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/gson/serializer/LocalDateSerializerTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/gson/serializer/StepAnnotationSerializerTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/gson/serializer/TestFeatureAnnotationSerializerTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/gson/serializer/TestScenarioAnnotationSerializerTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/gson/strategy/QtafGsonExclusionStrategyTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/TestSuiteLogCollectionTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/service/LogFileWriterTest.java
Labels: enhancement

#125 Bug/maven aws version missing
  pom.xml
  qtaf-aws-devicefarm/pom.xml
  qtaf-aws-devicefarm/src/main/java/de/qytera/qtaf/aws_devicefarm/config/AWSDeviceFarmConfigHelper.java
  qtaf-aws-devicefarm/src/main/java/de/qytera/qtaf/aws_devicefarm/driver/AWSChrome.java
  qtaf-aws-devicefarm/src/main/java/de/qytera/qtaf/aws_devicefarm/driver/AWSEdge.java
  qtaf-aws-devicefarm/src/main/java/de/qytera/qtaf/aws_devicefarm/driver/AWSFirefox.java
  qtaf-aws-devicefarm/src/main/java/de/qytera/qtaf/aws_devicefarm/driver/AbstractAWSDeviceFarmDriver.java
  qtaf-aws-devicefarm/src/test/java/de/qytera/qtaf/aws_devicefarm/config/AWSDeviceFarmConfigHelperTest.java
  qtaf-aws-devicefarm/src/test/java/de/qytera/qtaf/aws_devicefarm/driver/DriverTest.java
Labels: bug
