Repository Qytera-Gmbh/QTAF, pull requests merged in 2023-10, with the labels that each got.

#213 HTML templates are working and can display assertions now
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/base.html
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/feature.html
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/feature.inc.html
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/home.html
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/scenario.html
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/scenario.inc.html
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/scripts.js
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/step.inc.html
  qtaf-core/src/test/java/de/qytera/qtaf/core/events/EventSubscriberTest.java
  qtaf-html-report-plugin/src/test/java/de/qytera/qtaf/htmlreport/TemplateRendererTest.java
Labels: bug

#212 Add actual results to Xray results upload
  qtaf-core/src/main/java/de/qytera/qtaf/core/console/ConsoleColors.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/event_subscriber/step/StepLoggerSubscriber.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/guice/method_interceptor/QtafTestNGAnnotatedMethodInterceptor.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/AssertionLogMessage.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/log/model/message/StepInformationLogMessage.java
  qtaf-core/src/main/java/de/qytera/qtaf/testng/context/AssertionContext.java
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/base.html
  qtaf-core/src/main/resources/de/qytera/qtaf/htmlreport/templates/step.inc.html
  qtaf-core/src/main/resources/log4j2.xml
  qtaf-core/src/test/java/de/qytera/qtaf/core/console/TestConsoleColors.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/DemoStepClass.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/model/collection/TestScenarioLogCollectionTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/log/model/message/StepInformationLogMessageTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/selenium/DriverTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/testng/sample_test_classes/TestClass1.java
  qtaf-core/src/test/java/de/qytera/qtaf/testng/sample_test_classes/TestClass2.java
  qtaf-html-report-plugin/src/main/java/de/qytera/qtaf/htmlreport/event_subscriber/CreateReportSubscriber.java
  qtaf-testrail-plugin/src/main/java/de/qytera/qtaf/testrail/event_subscriber/UploadTestsSubscriber.java
  qtaf-testrail-plugin/src/test/java/de/qytera/testrail/event_subscriber/UploadTestsSubscriberTest.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/builder/test/XrayTestEntityBuilder.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestExecutionInfoEntity.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntity.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntityCloud.java
  qtaf-xray-plugin/src/main/java/de/qytera/qtaf/xray/entity/XrayTestInfoEntityServer.java
  qtaf-xray-plugin/src/test/java/de/qytera/qtaf/xray/builder/XrayJsonImportBuilderTest.java
Labels: 🛠 xray

#214 Errors now get correctly serialized
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/StackTraceElementSerializer.java
  qtaf-core/src/main/java/de/qytera/qtaf/core/gson/serializer/ThrowableWrapperSerializer.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/gson/serializer/StackTraceElementSerializerTest.java
  qtaf-core/src/test/java/de/qytera/qtaf/core/gson/serializer/ThrowableWrapperSerializerTest.java
Labels: bug

#226 Fix broken TestRail screenshot upload
  qtaf-http/src/main/java/de/qytera/qtaf/http/WebService.java
  qtaf-testrail-plugin/src/main/java/de/qytera/qtaf/testrail/event_subscriber/UploadTestsSubscriber.java
  qtaf-testrail-plugin/src/main/java/de/qytera/qtaf/testrail/utils/APIUtil.java
  qtaf-testrail-plugin/src/main/java/de/qytera/qtaf/testrail/utils/TestRailManager.java
  qtaf-testrail-plugin/src/test/java/de/qytera/qtaf/testrail/event_subscriber/UploadTestsSubscriberTest.java
  qtaf-testrail-plugin/src/test/java/de/qytera/qtaf/testrail/utils/APIUtilTest.java
  qtaf-testrail-plugin/src/test/java/de/qytera/qtaf/testrail/utils/ApiClientTest.java
  qtaf-testrail-plugin/src/test/java/de/qytera/qtaf/testrail/utils/Mocking.java
  qtaf-testrail-plugin/src/test/java/de/qytera/qtaf/testrail/utils/TestRailManagerTest.java
Labels: 🛠 testrail

#227 Bump QTAF from 0.2.7 to 0.2.8
  pom.xml
  qtaf-allure-plugin/pom.xml
  qtaf-aws-devicefarm/pom.xml
  qtaf-core/pom.xml
  qtaf-data/pom.xml
  qtaf-html-report-plugin/pom.xml
  qtaf-http/pom.xml
  qtaf-io/pom.xml
  qtaf-security/pom.xml
  qtaf-testrail-plugin/pom.xml
  qtaf-xray-plugin/pom.xml
Labels: version
