Repository Qytera-Gmbh/QTAF, pull requests merged in 2023-05, with the labels that each got.

#99 Add QTAF security plugin
  pom.xml
  qtaf-core/src/main/resources/qtaf.json
  qtaf-security/.gitignore
  qtaf-security/pom.xml
  qtaf-security/src/main/java/de/qytera/qtaf/security/aes/AES.java
  qtaf-security/src/test/java/de/qytera/qtaf/security/AESTest.java
Labels: enhancement, 🛠 security

#104 Change developer contact from `info@qytera.de` to `dev@qytera.de`
  pom.xml
Labels: bug, documentation

#108 Add dedicated release profile for deployment
  .github/workflows/Publish.yml
  pom.xml
Labels: enhancement

#111 Add sonar cloud quality analysis
  .github/workflows/Publish.yml
  .github/workflows/Test.yml
  pom.xml
Labels: enhancement
